version: '3'
services:
  toolkit:
    build: ./toolkit
    stdin_open: true
    tty: true
    hostname: TenagraTDK
    working_dir: /source
    volumes:
      - ../source:/source
  webserver:
    profiles:
      - webserver
    build: ./webserver
    volumes:
      - ../source:/source
  tftpserver:
    profiles:
      - tftpserver
    build: ./tftpserver
    volumes:
      - ../source:/source
